//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public int InvoiceItemID { get; set; }
        public int InvoiceID { get; set; }
        public int TreatmentID { get; set; }
        public int Quantity { get; set; }
        public decimal LineTotal { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
